### ISSUE TITLE
Can't login via github

### ISSUE THREAD

**Issue by alexarchambault** [ScalaIO/cfp-devoxx#3]
When trying to connect to the CfP via github on http://cfp.scala.io/home, I'm getting the following error:
```
Error : Désolé, nous ne pouvons importer votre profil depuis github. Veuillez modifier votre configuration github. L e-mail n'a pu être récupéré. Vous pouvez modifier votre configuration sur https://github.com/settings/profile
```

The application is well authorized though (I can see the just used `Scalaio-cfp` application from https://github.com/settings/applications)...

Same thing when trying again, before and after revoking / accepting again the application. And same thing from `https://cfp.scala.io/home` (https instead of http).

**Comment by jeantil** [comment]
Hello alexandre, 

I initially expected this to be linked to the https activation for cfp.scala.io but I just did a sanity check,tried logging in using my github account which was never used for the app and it worked just fine.

I'll review settings and logs now and let you know if I find anything.

**Comment by jeantil** [comment]
Re, 

I looked all over the settings and code but didn't find anything out of place. In the process I forced https everywhere rechecked every oauth url setup for all providers. 

Digging in the exact github process, we request the scope "user:email" when authorizing the app 
cf https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#1-users-are-redirected-to-request-their-github-identity

It seems the app complains that 
>L e-mail n'a pu être récupéré.
I am unsure which mail is effectively provided by github when using https://developer.github.com/v3/users/#get-the-authenticated-user but my tests seem to point to the public profile email (but I don't have an account without a public email to test this further) instead of the private email.

We need the email for 2 things 
- send you notifications (accepted talks, etc) 
- merge accounts across the various auth providers : the mail is the primary key for a speaker account in the cfp.

**Comment by alexarchambault** [comment]
Closing this as the cfp is about to close. Auth via github still wasn't working last time I tried, even though I gave the authorization, etc. But afaic, I'm able to create an account via email. Hopefully, I'm the only one to have run into this issue.
